### ISSUE TITLE
Progress bar at top of multistep - Information Request

### ISSUE THREAD

**Issue by rubyrubes** [timw255/RBMultistep#1]
I have managed to get the RBMultistep working. It looks great and is exactly what I wanted. I noticed on your youtube video that you had a nice visual progress bar at the top of the screen (with purple dots) but my version doesn't seem to show them. Could you tell me if you used any other styling?

**Comment by timw255** [comment]
I'm going to assume that rb.multistep.css is already included, otherwise it probably wouldn't be working at all. The only other thing I can think of is that the `navigation` option is set to `false`.

Can you post the code that's being used to initialize it?

**Comment by rubyrubes** [comment]
Thanks to your comment, i looked at the navigation section and found that my form was set to 'position' rather than 'bubble'. Everything seems to be working fine now apart from the submit button on the last page which is showing as disabled, after previously submitted errors have been fixed, Thanks for your help, much appreciated. I am new to Rollbase, javascript and jQuery!

$('form > table').multistepForm({
    labels: {
        next: 'Next',
        previous: 'Previous',
        submit: 'Submit'
    },
    navigation: {  // set to false for no navigation
        itemTemplate: '<span class="bubble">#position# </span><span class="title">#title#</span>',
        beforeNavigate: null
    },
    animation: {
        duration: 400 // set to false for no animations
    },
    progressTemplate: 'Step #position# of #total#',
    beforeNext: function (e) {
        if (!isValid()) {
            e.preventDefault();
        }
    },
    beforePrevious: null, // function to run before proceeding to the previous step ('Previous' button clicked)
    beforeSubmit: null, // function to run before submitting the form ('Submit' button clicked)
    maxWidth: null
});

**Comment by rubyrubes** [comment]
Hi Tim,
It seems to be working in Chrome, Firefox and the Edge browser but doesn't seem to work in IE.  A console javascript error is displayed in the '$.extend(MultistepForm.prototype' section indicating that ')' is expected. Greatly need your assistance as some people still use IE and it would need to be supported

Many thanks

**Comment by timw255** [comment]
I was able to reproduce this.

There were some issues with the code in IE. Will push updates soon.
